- name: Playbook de prueba  
  hosts: win19
  vars:
    limit: 268435456
  
  tasks:
        
  - name: Comprobando
    delegate_to: localhost
    stat:
      path: "/home/jjgutierrez/Desktop/bitbucket\ colombia/glgt-ap1289103-dev-lan-etl3-repo-container.zip"
    register: artifact
    failed_when: "'No existe' in artifact.stdout"
