- name: Playbook de prueba  
  hosts: win19
  vars:
    limit: 268435456
  
  tasks:
    
  - name: Descargar archivo en localhost
    delegate_to: localhost
    get_url:
      url: "https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi"
      dest: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi" 
 
  - name: Comprobar que se ha descargado el archivo en localhost
    delegate_to: localhost
    stat:
      path: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
    register: compdesc
    failed_when: compdesc.stat.exists == false
    
  - name: copiar archivo de localhost a host
    ansible.windows.win_copy:
      backup: yes
      src: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
      dest: "C:\\Users\\Administrador\\Desktop\\httpd-2.2.25-win32-x86-no_ssl.msi"
    register: copyhost
    failed_when: compdesc.stat.checksum != copyhost.checksum

  - name : Get Bluence home drive size
    ansible.windows.win_powershell:
      script: | 
        ((get-volume -DriveLetter C).SizeRemaining)
    register: BLUENCE_HOME_SIZE
    failed_when: BLUENCE_HOME_SIZE.output[0] < 268435456
    
  - name: Ver variable
    debug: var=BLUENCE_HOME_SIZE
    
  - name: Ver variable
    debug: var=BLUENCE_HOME_SIZE.output
    
  - name: Ver variable
    debug: var=BLUENCE_HOME_SIZE.output[0]
