- name: Playbook de prueba  
  hosts: win19
  vars:
    limit: 268435456
  
  tasks:
 
  - name: Descargar archivo en localhost
    delegate_to: localhost
    get_url:
      url: "https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi"
      dest: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi" 
    register: descarga
 
  - name: Comprobar que se ha descargado el archivo en localhost
    delegate_to: localhost
    stat:
      path: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
    register: compdesc
    when: descarga.size[0] > 10000
    failed_when: compdesc.stat.exists == false
    
  - name: copiar archivo de localhost a host
    ansible.windows.win_copy:
      backup: yes
      src: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
      dest: "C:\\Users\\Administrador\\Desktop\\httpd-2.2.25-win32-x86-no_ssl.msi"
    register: copyhost


  - name : Return my_folder
    debug: var=descarga
    
  - name : Return my_folder
    debug: var=compdesc
    
  - name : Return my_folder
    debug: var=copyhost
