- name: Playbook de prueba  
  hosts: win19
  vars:
    geoip_dir: "/tmp/geoip"
    geoip_db_url: "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz"
    geoip_db_md5sum_url: "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz.md5"
    geoip_db_compressed_file_name: "{{ geoip_db_url | basename }}"
    geoip_db_md5sum: "md5: {{ lookup('url', geoip_db_md5sum_url) }}"
  gather_facts: false
  tasks:
    
  - name: Descargar archivo en localhost
    delegate_to: localhost
    get_url:
      url: "https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi"
      dest: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi" 
 
  - name: Comprobar que se ha descargado el archivo en localhost
    delegate_to: localhost
    stat:
      path: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
    register: compdesc
    failed_when: compdesc.stat.exists == false
    
  - name: copiar archivo de localhost a host
    ansible.windows.win_copy:
      backup: yes
      src: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
      dest: "C:\\Users\\Administrador\\Desktop\\httpd-2.2.25-win32-x86-no_ssl.msi"
    register: copyhost
    failed_when: compdesc.stat.checksum != copyhost.checksum

  - name : Get Bluence home drive size
    ansible.windows.win_powershell:
      script: | 
        ((get-volume -DriveLetter C).SizeRemaining)
    register: BLUENCE_HOME_SIZE
    failed_when: BLUENCE_HOME_SIZE.output[0] < 268435456
    
  - name: Ver variable
    debug: var=BLUENCE_HOME_SIZE
    
  - name: Ver variable
    debug: var=BLUENCE_HOME_SIZE.output
    
  - name: Ver variable
    debug: var=BLUENCE_HOME_SIZE.output[0]

  - name: Create geoip directory if it doesn't exist
    file:
      path: "{{ geoip_dir }}"
      state: directory
      mode: 0700

  - name: "Downloading the latest GeoIP and comparing it to checksum {{ geoip_db_md5sum }}"
    get_url:
      url: "{{ geoip_db_url }}"
      dest: "{{ geoip_dir }}/{{ geoip_db_compressed_file_name }}"
      mode: 0600
      checksum: "{{ geoip_db_md5sum }}"
