- name: Playbook de prueba  
  hosts: win19
  vars:
    limit: 268435456
  
  tasks:
        
  - name: Comprobando
    delegate_to: localhost
    stat:
      path: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
    register: artifact
    failed_when: artifact.stat.exists == false


  - name : Return my_folder
    debug: var=artifact
