- name: Playbook de prueba  
  hosts: win19
  vars:
    limit: 268435456
  
  tasks:
 
 
  - name: Comprobar si existe Carpeta
    win_command: cmd.exe /c type C:\Users\Administrador\Desktop\httpd-2.2.25-win32-x86-no_ssl.msi
    register: existe
    
  - name: Descargar archivo en localhost
    delegate_to: localhost
    get_url:
      url: "https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi"
      dest: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi" 
    register: descarga
 
  - name: Comprobar que se ha descargado el archivo en localhost
    delegate_to: localhost
    stat:
      path: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
    register: compdesc
    failed_when: compdesc.stat.exists == false
    
  - name: copiar archivo de localhost a host
    ansible.windows.win_copy:
      backup: yes
      src: "/tmp/httpd-2.2.25-win32-x86-no_ssl.msi"
      dest: "C:\\Users\\Administrador\\Desktop\\httpd-2.2.25-win32-x86-no_ssl.msi"
    register: copyhost
    failed_when: compdesc.stat.checksum != copyhost.checksum




  - name : Return descarga
    debug: var=descarga
    
  - name : Return compdesc
    debug: var=compdesc
    
  - name : Return copyhost
    debug: var=copyhost
    
  - name : Return existe
    debug: var=existe

  - name : Return checksum
    debug: var="compdesc.stat.checksum"

  - name : Return checksum
    debug: var="copyhost.checksum"
