- hosts: win1
  collections:
    - community.windows
    - git

  tasks:
  
# Check temporal folder in localhost container
    - name: Ansible check project tmp directory
      delegate_to: localhost
      stat:
        path: /tmp/Descarga
      register: my_folder

    - name: "echo if project's last build directory already existed"
      delegate_to: localhost
      file:
        path: /tmp/Descarga
        state: absent
      when: my_folder.stat.exists

    - name: "Ansible Create Integration directory if not exists"
      delegate_to: localhost
      file:
        path: /tmp/Descarga
        state: directory
        mode: 0755
        recurse: true

# Download artifact from sources
    - name: Download last pinned build from TeamCity (INTEGRATION)
      delegate_to: localhost
      get_url:
        url: "http://teamcity.isotrol.net:8111/repository/downloadAll/Energia_Cerv4projects_Revergy_Aela_Cs_LibSceneModel_Build/.lastSuccessful/artifacts.zip?guest=1"
        dest: "/tmp/bluence_server_CS.zip"
      register: download1
# Check the Download last pinned build from TeamCity (INTEGRATION)
    - name: Check the discharge of artifact
      delegate_to: localhost
      stat:
        path: "/tmp/bluence_server_CS.zip"
      register: artifact1
      failed_when: download1.checksum_src != artifact1.stat.checksum
      changed_when: False

# Copy artifact from tmp to host (and check)
    - name: Copy File (Integration)
      ansible.windows.win_copy:
        backup: yes
        src: "/tmp/bluence_server_CS.zip"
        dest: "C:\Users\Administrador\Desktop\bluence_server_CS.zip"
      register: checksum1
      failed_when: artifact1.stat.checksum != checksum1.checksum
# Copy artifact and from tmp to host (and check)
#    - name: Copy File (Factory)
#      ansible.windows.win_copy:
#        backup: yes
#        src: "/tmp/Descarga"
#        dest: "C:\Users\Administrador\Desktop\"
      
 
