- hosts: win1
  collections:
    - community.windows
    - ansible.builtin.git

  tasks:

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/jjgl93/server.git'
        dest: /tmp
        archive: /tmp/git.zip
#    - git:
#        repo: git://foosball.example.org/path/to/repo.git
#        dest: /srv/checkout
#        version: dev
