- hosts: win1
  collections:
    - community.windows
    
  tasks:
  
    - name: Git checkout
      delegate_to: localhost
      ansible.builtin.git:
        repo: https://github.com/jjgl93/server.git
        dest: /tmp
        archive: /tmp/prueba_git.zip
        version: v1

    - name: Copy File
      ansible.windows.win_copy:
        src: "/tmp/prueba_git.zip"
        dest: "C:\Users\Administrador\Desktop\git.zip"
