- hosts: win1
  collections:
    - community.windows
    - git

  tasks:

    - name: Deploy site files from Github repository
      sudo: yes
      git: repo=git@github.com:jjgl93/server.git dest=/tmp
  
#    - git:
#        repo: git://foosball.example.org/path/to/repo.git
#        dest: /srv/checkout
#        version: dev
