- hosts: win1
  collections:
    - community.windows
    
  tasks:
  
    - name: Ansible check project tmp directory
      delegate_to: localhost
      stat:
        path: /tmp/Descarga-Git
      register: my_folder

    - name: "echo if project's last build directory already existed"
      delegate_to: localhost
      file:
        path: /tmp/Descarga-Git
        state: absent
      when: my_folder.stat.exists

    - name: "Ansible Create Integration directory if not exists"
      delegate_to: localhost
      file:
        path: /tmp/Descarga-Git
        state: directory
        mode: 0755
        recurse: true
        
    - name: Git checkout
      delegate_to: localhost
      ansible.builtin.git:
        repo: 'https://github.com/jjgl93/server.git'
        dest: '/tmp/Descarga-Git'
        version: v1
        archive: '/tmp/Descarga-Git/git.zip'

    - name: copiar archivo de localhost a host
      ansible.windows.win_copy:
        backup: yes
        src: "/tmp/Descarga-Git/git.zip"
        dest: "C:\\Users\\Administrador\\Desktop\\"

    - name: Extract packages with powershell module
      ansible.windows.win_powershell:
        script: |
          Expand-7Zip -ArchiveFileName 'C:\\Users\\Administrador\\Desktop\\git.zip' -TargetPath 'C:\\Users\\Administrador\\Desktop\\git_tmp'
