- hosts: win1
  collections:
    - community.windows
    
  tasks:
  
    - name: Extract packages with powershell module
      ansible.windows.win_powershell:
        script: |
          Get-ChildItem -Path C:\Users\Administrador\Desktop\ *.lnk
      register: enlace
      
    - name: Print Bluence version and target version
      debug: var=enlace
