- hosts: win
  collections:
    - community.windows

  tasks:
  
# Check temporal folder in localhost container
    - name: Ansible check project tmp directory
      delegate_to: localhost
      stat:
        path: /tmp/Descarga
      register: my_folder

    - name: "echo if project's last build directory already existed"
      delegate_to: localhost
      file:
        path: /tmp/Descarga
        state: absent
      when: my_folder.stat.exists

    - name: "Ansible Create Integration directory if not exists"
      delegate_to: localhost
      file:
        path: /tmp/Descarga
        state: directory
        mode: 0755
        recurse: true

- name: Example clone of a single branch
  ansible.builtin.git:
    repo: https://github.com/jjgl93/server.git
    dest: /tmp/Descarga
    single_branch: yes
    version: v4

# Copy artifact and from tmp to host (and check)
#    - name: Copy File (Factory)
#      ansible.windows.win_copy:
#        backup: yes
#        src: "/tmp/Descarga"
#        dest: "C:\Users\Administrador\Desktop\"
      
