- hosts: win1
  collections:
    - community.windows
    
  tasks:
  
    - name: Git checkout
      delegate_to: localhost
      ansible.builtin.git:
        repo: https://github.com/jjgl93/server.git
        dest: /tmp
        archive: /tmp/prueba_git.zip
        version: v1

    - name: copiar archivo de localhost a host
      ansible.windows.win_copy:
        backup: yes
        src: "/tmp/prueba_git.zip"
        dest: "C:\\Users\\Administrador\\Desktop\\prueba_git.zip"
      register: copyhost
