- name: Playbook de prueba  
  hosts: win19
  
  tasks:
        
  - name: Comprobando que el sistema es Server 2019
    win_command: cmd.exe /c systeminfo | find /i "Sistema Operativo"
    register: version
    failed_when: "'Windows Server 2019' not in version.stdout"
    changed_when: False
    
    
  - name: Comprobando que el sistema es Server 2019
    win_command: cmd.exe /c SET BLUENCE_HOME
    register: HDD

  - name: Ver variable
    debug: var=HDD
    
  - name: Comprobar memoria si está en D:\
    win_command: cmd.exe /c "fsutil volume diskfree c:"
    register: memory
    failed_when: "'D:\' not in HDD.stdout"
    changed_when: False

  - name: Ver variable
    debug: var=memory
