- name: Playbook de prueba  
  hosts: win19
  
  tasks:
        
  - name: Comprobando que el sistema es Server 2019
    win_command: cmd.exe /c systeminfo | find /i "Sistema Operativo"
    register: version
    failed_when: "'Windows Server 2019' not in version.stdout"
    changed_when: False
    
    
  - name: Comprobando valor variable de entorno
    win_command: cmd.exe /c SET BLUENCE_HOME
    register: HDD

  - name: Ver variable
    debug: var=HDD
    
  - name: Guardar memoria en txt
    ansible.windows.win_powershell:
      script: |
        Get-WmiObject -Class Win32_LogicalDisk | Select-Object -Property  @{Label="a"; expression={($_.FreeSpace/1GB).ToString('F2')}}|ft > C:\Users\Administrador\Desktop\memoria.txt
    


  - name: Ver variable
    debug: var=memory
