  hosts: all
  tasks: 
    - 
      copy: ~
      delegate_to: localhost
      name: "Copy a single file"
       src: /home/jjgutierrez/Escritorio/copy.txt
       dest: /home/usuario/Desktop/copy.txt
       remote_src: yes
