- hosts: all
  tasks:
  - name: Copy a single folder
    win_copy:
      src: C:\Users\Administrador\Downloads\copy
      dest: C:\Users\Administrador\Desktop
      remote_src: yes
      
  - name: Copy a single file
    delegate_to: localhost
    ansible.windows.win_copy:
      src: /home/copy.txt
      dest: C:\Users\Administrador\Desktop\copy.txt
