- name: Playbook de prueba  
  hosts: all
  vars:
    archivo1: copy.txt
    directorio: copy
    
  tasks:
  
  - name: Comprobando que el sistema es Server 2019
    win_command: cmd.exe /c systeminfo | find /i "Sistema Operativo"
    register: version
    failed_when: "'Windows Server 2019' not in version.stdout"
    changed_when: False
    
  - name: Comprobación fichero en descargas
    win_command: cmd.exe /c cd C:\Users\Administrador\Downloads & dir
    register: result
    failed_when: 
      - "'1 archivos' not in result.stdout"
      -  result.rc != 0
    changed_when: False

  - name: Crear Directorio
    ansible.windows.win_file:
      path: 'C:\Users\Administrador\Downloads\{{ directorio }}'
      state: directory
   
  - name: Crear Archivo
    ansible.windows.win_file:
      path: 'C:\Users\Administrador\Downloads\{{ archivo1 }}'
      state: touch
      
  - name: Copiar Directorio
    win_copy:
      src: C:\Users\Administrador\Downloads\{{ directorio }}
      dest: C:\Users\Administrador\Desktop
      remote_src: yes

  - name: Copiar Archivo
    win_copy:
      src: 'C:\Users\Administrador\Downloads\{{ archivo1 }}'
      dest: 'C:\Users\Administrador\Desktop\{{ archivo1 }}'
      remote_src: yes

  - name: Crear Directorio
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy2
      state: directory
    
  - name: Crear archivo con CMD
    win_command: cmd.exe /c type nul > C:\Users\Administrador\Desktop\copy2\prueba.txt

  - name: Borrar archivo si existe
    ansible.windows.win_file:
      path: 'C:\Users\Administrador\Desktop\{{ archivo1 }}'
      state: absent
    
  - name: Borrar Directorio
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy2
      state: absent
     
  - name: Borrar Directorio
    ansible.windows.win_file:
      path: 'C:\Users\Administrador\Desktop\{{ directorio }}'
      state: absent
    
  - name: Prueba de arhivo inexistente para ignorar error
    win_command: cmd.exe /c type C:\Users\Administrador\Desktop\running.txt  
    register: existe
    ignore_errors: true

  - name: Descargar MSI
    win_get_url:
      url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: C:\Users\Administrador\Desktop\httpd-2.2.25-win32-x86-no_ssl.msi
  
  - name: Parar servicio
    win_service:
      name: FontCache
      state: stopped
    
  - name: Arrancar servicio
    win_service:
      name: FontCache
      state: Started 
      
  - name: Añadir variable de entorno
    win_environment:
      state: present
      name: NewVariable
      value: New Value
      level: machine
    
  - name: CMD command
    win_command: cmd.exe /c sc query > C:\Users\Administrador\Desktop\running_services.txt  
    register: services1
    failed_when: "'FAILED' in services1.stderr"
    
  - name: CMD command
    win_command: cmd.exe /c ipconfig > C:\Users\Administrador\Desktop\datos_red.txt  
    register: services2
    failed_when: "'FAILED' in services2.stderr"
    
      
  - name: Copiar archivo haciendo backup
    ansible.windows.win_copy:
      src: C:\Users\Administrador\Desktop\datos_red.txt
      dest: C:\Users\Administrador\Downloads\datos_red.txt 
      backup: yes 
      remote_src: yes

  - name: Ver variable
    debug: var=services2
