- hosts: win
  tasks:
  - name: Copy a single file
    ansible.windows.win_copy:
      src: C:\Users\Administrador\Downloads\copy.txt
      dest: C:\Users\Administrador\Desktop\copy.txt
      remote_src: yes
