- name: Playbook de prueba  
  hosts: win1
    
  tasks:

  - name: Update soft link with powershell module
    ansible.windows.win_powershell:
      script: |
        New-Item -ItemType SymbolicLink -Path 'C:\Users\Administrador\Desktop\link1' -Target 'C:\Users\Administrador\Desktop\Path'  -Force

  - name: Update soft link with powershell module
    ansible.windows.win_powershell:
      script: |
        New-Item -ItemType SymbolicLink -Path 'C:\Users\Administrador\Desktop\link2' -Target 'C:\Users\Administrador\Desktop\Path'  -Force
        
# Check sof link
  - name: check soft link
    ansible.windows.win_powershell:
      script: |
        cd 'C:\Users\Administrador\Desktop'; (Get-ChildItem | ? Target).Target
    register: nlink
    failed_when: nlink.output is null
    changed_when: False

  - name: ver variable
    debug: var=nlink

# Check sof link
  - name: check soft link
    ansible.windows.win_powershell:
      script: |
        cd 'C:\Users\Administrador'; (Get-ChildItem | ? Target).Target
    register: n2link
    failed_when: n2link.output is null
    changed_when: False

  - name: ver variable
    debug: var=n2link
