--- 
- 
  hosts: win
  tasks: 
    - 
      ansible.windows.win_copy: 
        dest: "C:\\Users\\Administrador\\Desktop\\copy.txt"
        remote_src: true
        src: "C:\\Users\\Administrador\\Downloads\\copy.txt"
      name: "Copy a single file"
