- hosts: all
  tasks:
  - name: Copy a single file
    copy:
      delegate_to: localhost
      src: /home/jjgutierrez/Escritorio/copy.txt
      dest: /home/usuario/Desktop/copy.txt
      remote_src: yes
