- hosts: all
  tasks:
  
  - name: Comprobación de sistema
    win_command: cmd.exe /c systeminfo | find /i "Sistema Operativo"
    register: version
    failed_when: "'Windows Server 2019' not in version.stdout"
    changed_when: False
    
  - name: Comprobación ficheros en descargas
    win_command: cmd.exe /c cd C:\Users\Administrador\Downloads & dir
    register: result
    failed_when: 
      - "'1 archivos' not in result.stdout"
      -  result.rc != 0
    changed_when: False


  - name: Copy folder
    win_copy:
      src: C:\Users\Administrador\Downloads\copy
      dest: C:\Users\Administrador\Desktop
      remote_src: yes

  - name: Copy file
    win_copy:
      src: 'C:\Users\Administrador\Downloads\copy.txt'
      dest: 'C:\Users\Administrador\Desktop\copy.txt'
      remote_src: yes

  - name: Create directory
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy2
      state: directory
    
  - name: Create file cmd command
    win_command: cmd.exe /c type nul > C:\Users\Administrador\Desktop\copy2\prueba.txt

  - name: Remove a file, if present
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy.txt
      state: absent
    
  - name: Remove directory
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy2
      state: absent
     
  - name: Remove directory
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy
      state: absent
    
  - name: Prueba de arhivo inexistente para ignorar error
    win_command: cmd.exe /c type C:\Users\Administrador\Desktop\running.txt  
    register: existe
    ignore_errors: true

  - name: Download the Apache installer
    win_get_url:
      url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: C:\Users\Administrador\Desktop\httpd-2.2.25-win32-x86-no_ssl.msi

  - name: Install MSI
    win_package: 
      path: C:\Users\Administrador\Desktop\httpd-2.2.25-win32-x86-no_ssl.msi
      arguments:
        - /install
        - /passive
        - /norestart

    
  - name: CMD command
    win_command: cmd.exe /c sc query > C:\Users\Administrador\Desktop\running_services.txt  
    register: services1
    failed_when: "'FAILED' in services1.stderr"
    
  - name: CMD command
    win_command: cmd.exe /c ipconfig > C:\Users\Administrador\Desktop\datos_red.txt  
    register: services2
    failed_when: "'FAILED' in services2.stderr"

  - name: Ver variable
    debug: var=datred
