- name: Playbook de prueba  
  hosts: rtu
  vars:
    archivo1: copy.txt
    directorio: copy
    
  tasks:

  - name: Crear Directorio
    ansible.windows.win_file:
      path: 'C:\Users\Administrador\Desktop\{{ directorio }}'
      state: directory
