- hosts: all
  tasks:
  - name: Copy a single folder
    win_copy:
      src: C:\Users\Administrador\Downloads\copy
      dest: C:\Users\Administrador\Desktop
      
  - name: Copy a single file
    win_copy:
      src: 'C:\Users\Administrador\Downloads\copy.txt'
      dest: 'C:\Users\Administrador\Desktop\copy.txt'

  - name: Run a cmd command
    win_command: cmd.exe /c mkdir C:\Users\Administrador\Desktop\copy2
    
  - name: Run a cmd command
    win_command: cmd.exe /c type nul > C:\Users\Administrador\Desktop\copy2\prueba.txt
