- hosts: all
  tasks:
  - name: Copy a single file
    delegate_to: localhost
    win_copy:
      src: /home/jjgutierrez/Escritorio/copy.txt
      dest: C:\Users\Administrador\Desktop\copy.txt
      remote_src: yes
