- hosts: all
  tasks:
  
  - name: Comprobación de sistema
    win_command: cmd.exe /c systeminfo | find /i "Sistema Operativo"
    register: version
    failed_when: "'Windows Server 2019' not in version.stdout"
    changed_when: False
    
  - name: Comprobación ficheros en descargas
    win_command: cmd.exe /c dir *.* /w / C:\Users\Administrador\Downloads
    register: result
    failed_when: result.rc != 1
    changed_when: False


  - name: Copy folder
    win_copy:
      src: C:\Users\Administrador\Downloads\copy
      dest: C:\Users\Administrador\Desktop
      remote_src: yes

  - name: Copy file
    win_copy:
      src: 'C:\Users\Administrador\Downloads\copy.txt'
      dest: 'C:\Users\Administrador\Desktop\copy.txt'
      remote_src: yes

  - name: Create directory
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy2
      state: directory
    
  - name: Create file cmd command
    win_command: cmd.exe /c type nul > C:\Users\Administrador\Desktop\copy2\prueba.txt

  - name: Remove a file, if present
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy.txt
      state: absent
    
  - name: Remove directory
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy2
      state: absent
     
  - name: Remove directory
    ansible.windows.win_file:
      path: C:\Users\Administrador\Desktop\copy
      state: absent
           
  - name: CMD command
    win_command: cmd.exe /c ipconfig > C:\Users\Administrador\Desktop\datos_red.txt
    
  - name: CMD command
    win_command: cmd.exe /c type C:\Users\Administrador\Desktop\running.txt  
    register: existe
    ignore_errors: true

  - name: CMD command
    win_command: cmd.exe /c sc query > C:\Users\Administrador\Desktop\running_services.txt  
    register: services
    failed_when: "'FAILED' in services.stderr"

  - name: Ver variable
    debug: var=result
