- name: Playbook de prueba  
  hosts: win1
    
  tasks:

  - name: Crear Directorio
    ansible.windows.win_file:
      path: 'C:\Users\Administrador\Desktop\{{ directorio }}'
      state: directory
