- name: Playbook de prueba  
  hosts: win19
  tasks:
    
  - name: Ansible check project tmp directory
    delegate_to: localhost
    stat:
      path: /tmp/bluence_server_latest
    register: my_folder

  - name: "echo if project's last build directory already existed"
    delegate_to: localhost
    file:
      path: /tmp/bluence_server_latest
      state: absent
    when: my_folder.stat.exists
